export const ADD_TODO = 'ADD_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const ADD_GOAL = 'ADD_GOAL'
export const REMOVE_GOAL ='REMOVE_GOAL'
export const RECEIVE_DATA = 'RECEIVE_DATA'
